"""
Django settings for imgbackend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path
from decouple import config
from dotenv import load_dotenv
import mongoengine
import cloudinary
import cloudinary.uploader
import cloudinary.api
import os

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

cloudinary.config(
    cloud_name="dxsafjcl4",
    api_key="734289539815585",
    api_secret="CBZPRw57UsYIVPM13VZuio9wbCQ",
    secure=True
)

# Keep a sane default for local development but prefer environment variable
DEFAULT_GOOGLE_API_KEY = "AIzaSyBDxOUjKGoEd2STxXXMJmnSd1MF0hCMx0E"
GOOGLE_API_KEY = config('GOOGLE_API_KEY', default=DEFAULT_GOOGLE_API_KEY)

# Razorpay Configuration
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5lq_q+khpb)*(zl57h+0ha*2ptm%_ruj9unofbc4v*z(^=af4@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]',
                 "api.gosplash.ai", "tarnika-frontend.vercel.app"]

# user = os.environ["MONGO_USER"]
# password = os.environ["MONGO_PASSWORD"]
uri = f"mongodb+srv://bhargavraavi4444_db_user:bhargav4444@cluster0.5dfeawc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
# uri = f"mongodb+srv://swethab9392_db_user:Swetha2003@cluster0.qtnsdub.mongodb.net/?appName=Cluster0"

# print("user", user)
# print("passsweord", password)
# Connect MongoEngine (MongoDB)
try:
    mongoengine.connect(
        db='tarnika',
        host=uri,

    )
    # Force check connection
    mongoengine.connection.get_connection().server_info()
    print("✅ MongoDB connection successful!")
except Exception as e:
    print("❌ MongoDB connection failed:", e)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'imgbackendapp',
    'probackendapp',
    "users",
    'organization',
    'CREDITS',
    'payments',
    'django_celery_results',
]


CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
# Use MongoDB as result backend to store task results
# Construct MongoDB URL for Celery from existing URI
mongodb_db_name = 'tarnika'
# Replace the query string part and add database name
celery_mongodb_uri = uri.replace('/?', f'/{mongodb_db_name}?')
CELERY_RESULT_BACKEND = celery_mongodb_uri
CELERY_MONGODB_BACKEND_SETTINGS = {
    'database': mongodb_db_name,
    'taskmeta_collection': 'celery_taskmeta',
}
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
# Prevent automatic deletion of task results
CELERY_TASK_RESULT_EXPIRES = None

# Use multiple worker processes to take advantage of multi-core VPS.
# You can override this at runtime with the -c flag on the worker.
CELERY_WORKER_CONCURRENCY = int(os.getenv("CELERY_WORKER_CONCURRENCY", "4"))


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_HEADERS = True
CORS_ALLOW_ALL_METHODS = True

CORS_ALLOW_NON_SIMPLE_HEADERS = True
CORS_ALLOW_PRIVATE_NETWORK = True

CORS_EXPOSE_HEADERS = ['*']
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",

    # For local testing without ports
    "http://localhost",
    "http://127.0.0.1",

    # Vercel frontend
    "https://tarnika-frontend.vercel.app",
]


ROOT_URLCONF = 'imgbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates' / 'imgbackendapp' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'imgbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded by users)
# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings for frontend integration


# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://tarnika-frontend.vercel.app",
    "https://backend.gosplash.ai",
    "https://api.gosplash.ai",   # <-- add this
]


CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

# Email Configuration (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# Frontend URL for password reset links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')
